
export const posters=[
    {   id:0,
        name:"Berlin",
        url:"/img/img1.png",
        category:"Movie",
        description:"   This is a poster",
        creator:"Sainath"
    },
    {   id:1,
        name:"BMW E-90",
        url:"/img/img2.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:2,
        name:"Esclade",
        url:"/img/img3.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:3,
        name:"GLE 300D",
        url:"/img/img4.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:4,
        name:"Hitler",
        url:"/img/img5.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:5,
        name:"Iron Balls",
        url:"/img/img6.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:6,
        name:"Joker",
        url:"/img/img7.png",
        category:"Horror",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:7,
        name:"MG Gloster",
        url:"/img/img8.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:8,
        name:"Moshin Swift",
        url:"/img/img9.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:9,
        name:"Creative",
        url:"/img/img10.png",
        category:"Creative",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:10,
        name:"Nexon",
        url:"/img/img11.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:11,
        name:"Tigor",
        url:"/img/img12.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:12,
        name:"GTR R34",
        url:"/img/img13.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:13,
        name:"Roler Oyster Perpetual 41",
        url:"/img/img14.png",
        category:"Watch",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:14,
        name:"Siddhu Moose Wala",
        url:"/img/img15.png",
        category:"Music",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:15,
        name:"Super Man",
        url:"/img/img16.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:16,
        name:"Swift Dzire",
        url:"/img/img17.png",
        category:"car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:17,
        name:"Tejas MK2",
        url:"/img/img18.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:18,
        name:"Bala Saheb Thakrey",
        url:"/img/img19.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:19,
        name:"The Boys",
        url:"/img/img20.png",
        category:"Action",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:20,
        name:"Fortuner",
        url:"/img/img21.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    {   id:21,
        name:"Xuv 700",
        url:"/img/img22.png",
        category:"Car",
        description:"This is a poster",
        creator:"Sainath"
    },
    
]

export const sliders=[
    {   id:1,
        name:"Koenigsegg Jesko",
        url:"/img/slider1.png",
        category:"Car",
        description:"This is a poster",
    },
    {
        id:2,
        name:"BMW 5M CS",
        url:"/img/slider2.png",
        category:"Car",
        description:"This is a poster",
    },
    {
        id:3,
        name:"BMW S1000 RR",
        url:"/img/slider3.png",
        category:"Car",
        description:"This is a poster",
    },
]